### ISSUE TITLE
Error message "Cannot read property 'forEach' of undefined" on startup

### ISSUE THREAD

**Issue by mbartosch** [pbegg/signalk-to-influxdb-v2-buffering#16]
I just installed this module in my SignalK docker instance and configured a locally hosted InfluxDB 2.x database (also via docker). 

I tested this with the InfluxDB2 Plugin config Host URL set to http://localhost and http://localhost:8086

The InfluxDB2 database can be pinged OK from the SignalK docker container via 
influx ping --host http://localhost:8086
OK

On startup I get the following error message:

Aug 13 08:58:55 error starting plugin: TypeError: Cannot read property 'forEach' of undefined
Aug 13 08:58:55 TypeError: Cannot read property 'forEach' of undefined at Object._start [as start] (/home/node/.signalk/node_modules/signalk-to-influxdb-v2-buffering/index.js:120:25) at doPluginStart (/home/node/signalk/lib/interfaces/plugins.js:265:20) at doRegisterPlugin (/home/node/signalk/lib/interfaces/plugins.js:388:13) at registerPlugin (/home/node/signalk/lib/interfaces/plugins.js:219:13) at modulesWithKeyword.forEach (/home/node/signalk/lib/interfaces/plugins.js:170:13) at Array.forEach (<anonymous>) at startPlugins (/home/node/signalk/lib/interfaces/plugins.js:169:63) at Object.start (/home/node/signalk/lib/interfaces/plugins.js:55:13) at /home/node/signalk/lib/index.js:363:70 at /home/node/signalk/node_modules/lodash/lodash.js:4967:15 at Function.forIn (/home/node/signalk/node_modules/lodash/lodash.js:13018:11) at startInterfaces (/home/node/signalk/lib/index.js:353:7) at /home/node/signalk/lib/index.js:273:13 at createServer (/home/node/signalk/lib/index.js:317:5) at Promise (/home/node/signalk/lib/index.js:262:9) at new Promise (<anonymous>) at Server.start (/home/node/signalk/lib/index.js:261:12) at Object.<anonymous> (/home/node/signalk/bin/signalk-server:26:8) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by landler** [comment]
I realize it's a long time since this issue was posted, but for anyone who might end up here looking for a solution: the forEach is attempting to loop through the default tags, and if none are added it errors out - so you can fix this by just adding a dummy tag to the default tags in the plugin config.
