### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by tkwp** [pbegg/signalk-to-influxdb-v2-buffering#6]
Hallo,
I try to run your plugin on a Raspi 4, but can not start as the above error is displayed. I followed the official installation guide from Signal-K on Github.

Your support is appreciated.
Regards, Thomas

----------------------------------------------------
signalk-to-influxdb-v2-buffering failed to start: Cannot find module 'debug'
{ Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/.signalk/node_modules/signalk-to-influxdb-v2-buffering/buffer.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/.signalk/node_modules/signalk-to-influxdb-v2-buffering/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }

**Comment by pbegg** [comment]
I will have to have a look into this one. 
Does the same error come up everytime you restart the server or the plugin?

**Comment by pbegg** [comment]
Updated to new Version.
