### ISSUE TITLE
Not writing to buffer

### ISSUE THREAD

**Issue by seasharp33** [pbegg/signalk-to-influxdb-v2-buffering#8]
I have this setup on a Pi4 running the openplotter.  I have created the /home/pi/signalkbuffer and all is working with sending information to my bucket.   When I cause a interruption form the internet connection I do not see batches being created.  Then when I reconnect to the internet there is a gap in my data.  do you have a sample configuration file I don't see any reference to the buffer path in there.  I configured the plugin via the signalk console.

Thank you for building this it is exactly what I have been looking for to monitor my boat that is currently in an area with spotty wifi

**Comment by pbegg** [comment]
I need to update the read me. If you have downloaded the latest version of the plugin the buffering should be handled by the influx JavaScript library. 
I can disconnect from the internet and reconnect and the buffered data will be uploaded. 
There is no buffer created in that directory mentioned in the readme anymore.

**Comment by MichaelHviid** [comment]
Hi pbegg, what a great tool for the boat - thank you...

unfortunatly mine does now buffer when I loose connection to the internet ... is there a way to check the local buffer ... at the moment it is not specified in any configuration-files ...

I just get this in my log when the connection is offline : (192.168.30.8 is my InfluxDB hosted on land, connected with VPN)
May 10 21:51:49 WARN: Write to InfluxDB failed (remaining attempts: 3). { Error: connect ECONNREFUSED 192.168.30.8:8086 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14) errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '192.168.30.8', port: 8086 }
May 10 21:51:55 WARN: Write to InfluxDB failed (remaining attempts: 2). { Error: connect ECONNREFUSED 192.168.30.8:8086 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14) errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '192.168.30.8', port: 8086 }
May 10 21:52:00 WARN: Write to InfluxDB failed (remaining attempts: 1). { Error: connect ECONNREFUSED 192.168.30.8:8086 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14) errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '192.168.30.8', port: 8086 }

**Comment by pbegg** [comment]
The plugin used to use a local buffer. This is now handled by the influx JavaScript library.
For my tests it has been working, this is with internet down time of around 5minutes. 
Is it uploading any of your data when it reconnects?

**Comment by MichaelHviid** [comment]
It does not look like it, it is just missing the data - do you know where to look for the buffer?

**Comment by pbegg** [comment]
What version of the plugin are you running?

**Comment by MichaelHviid** [comment]
2.0.2 and InfluxDB is 2.0.5 - I am not sure if I have installed any other local clients ... or if they were nessary

**Comment by pbegg** [comment]
I have only tested this with influx cloud not influx open source.

What if you change the max retries parameter to a high number like 100 and try again?

**Comment by MichaelHviid** [comment]
hmmm  - ok, let me try different options - let it be for now, I am sailing again tomorrow.

thank you for your help for now.

regards
Michael

**Comment by xbgmsharp** [comment]
I have the same issue, the buffer is not working anymore since the influx JavaScript library.

**Comment by mgf909** [comment]
Same here - if i shutdown influxdb or disable the network, nothing is buffered ;-( 
no files are created in /home/pi/signalkbuffer

**Comment by leeprevost** [comment]
@pbegg -- I also really appreciate this module.   I think from reading the above, this does not currently support the influxdb2.x oss local database yet.   

What I'm hoping to do:
- Log local n2k points on influxdb2.x  (the reason I think I need version 2.x is I want to do math across measurements and do some anomoly detection -- version 2.x seems to support that better with flux queries and tasks).  
- When I'm in port, upload downsampled and transformed data that was processed by the local db.

Altough I'm a python guy, I'd be glad to pitch in and help.  It looks like the new js drivers you are using will support the local oss db.   I also have been using the oss version 1.8 and the older plug-in and this works great but I can't really do local processing across measurements at least that I can see.   

If you could point me to how to approach it, I'd be glad to fork it and try.

Lee
